"""
Document Generation — PDF export, customizable templates, formatted output.

Generates documents in Markdown, HTML, or PDF format with support for:
- Email drafts
- Reports
- Summaries
- Government forms (Aadhaar, PAN applications)
- Code snippets
"""

import os
import json
import logging
from datetime import datetime
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

TEMPLATES = {
    "email": {
        "name": "Email Draft",
        "format": """Subject: {subject}\n\nDear {recipient},\n\n{body}\n\nBest regards,\n{sender}""",
        "fields": ["subject", "recipient", "body", "sender"],
    },
    "report": {
        "name": "Report",
        "format": """# {title}\n\n**Date:** {date}\n**Author:** {author}\n\n---\n\n{body}\n\n---\n\n*Generated by Zenix AI*""",
        "fields": ["title", "date", "author", "body"],
    },
    "summary": {
        "name": "Summary",
        "format": """## {title}\n\n{body}\n\n*Summary generated on {date}*""",
        "fields": ["title", "body", "date"],
    },
    "form_letter": {
        "name": "Form Letter",
        "format": """{date}\n\n{recipient_name}\n{recipient_address}\n\nSubject: {subject}\n\nDear {recipient_name},\n\n{body}\n\nSincerely,\n{sender_name}""",
        "fields": ["date", "recipient_name", "recipient_address", "subject", "body", "sender_name"],
    },
    "code": {
        "name": "Code Snippet",
        "format": """# {title}\n\n```{language}\n{code}\n```\n\n## Explanation\n\n{explanation}""",
        "fields": ["title", "language", "code", "explanation"],
    },
    "memo": {
        "name": "Internal Memo",
        "format": """MEMORANDUM\n\nTO: {to}\nFROM: {from_name}\nDATE: {date}\nRE: {subject}\n\n{body}""",
        "fields": ["to", "from_name", "date", "subject", "body"],
    },
    "rental_agreement": {
        "name": "Rental Agreement",
        "format": """# RENTAL AGREEMENT\n\nThis Rental Agreement is made on {date} between:\n\n**LANDLORD:** {landlord_name}, S/o/D/o {landlord_father}, Aged {landlord_age} years, residing at {landlord_address}\n\n**TENANT:** {tenant_name}, S/o/D/o {tenant_father}, Aged {tenant_age} years, residing at {tenant_address}\n\n## Property Details\n- Address: {property_address}\n- Area: {area_sqft} sq. ft.\n- Type: {property_type}\n\n## Terms & Conditions\n1. Monthly Rent: Rs {rent_amount} payable by {rent_due_date} of each month\n2. Security Deposit: Rs {deposit_amount} (refundable at end of tenancy)\n3. Lock-in Period: {lock_in_months} months\n4. Notice Period: {notice_period} months from either party\n5. Maintenance: Minor repairs by tenant, major by landlord\n6. Electricity/Water: Paid by tenant directly\n7. Subletting: Not permitted without written consent\n8. Police Verification: To be completed within 7 days\n9. Agreement Duration: {agreement_duration} months (renewable)\n\n## Signatures\n\nLandlord: _________________ Date: _________\n\nTenant: _________________ Date: _________\n\nWitness 1: _________________\n\nWitness 2: _________________""",
        "fields": ["date", "landlord_name", "landlord_father", "landlord_age", "landlord_address", "tenant_name", "tenant_father", "tenant_age", "tenant_address", "property_address", "area_sqft", "property_type", "rent_amount", "rent_due_date", "deposit_amount", "lock_in_months", "notice_period", "agreement_duration"],
    },
    "sale_deed": {
        "name": "Sale Deed",
        "format": """# SALE DEED\n\nThis Sale Deed is executed on {date} between:\n\n**VENDOR (Seller):** {seller_name}, S/o {seller_father}, Aged {seller_age} years, residing at {seller_address}\n\n**VENDEE (Buyer):** {buyer_name}, S/o {buyer_father}, Aged {buyer_age} years, residing at {buyer_address}\n\n## 1. Property Description\n- Property: {property_address}\n- Survey/Plot No: {survey_number}\n- Area: {area_sqft} sq. ft.\n- Boundaries: North: {boundary_north}, South: {boundary_south}, East: {boundary_east}, West: {boundary_west}\n\n## 2. Sale Consideration\n- Total Sale Price: Rs {sale_price} (Rupees {sale_price_words})\n- Payment Mode: {payment_mode}\n- Token Amount: Rs {token_amount} paid on {token_date}\n\n## 3. Seller's Covenants\n- Seller has clear, marketable title\n- Property is free from encumbrances\n- Seller has right to sell\n\n## 4. Buyer's Covenants\n- Buyer has inspected property\n- Buyer accepts property as-is\n- Buyer will pay stamp duty and registration\n\n## 5. Possession\n- Date of possession: {possession_date}\n- Property delivered vacant and peaceful\n\n## Signatures\n\nVendor: _________________ Date: _________\n\nVendee: _________________ Date: _________\n\nWitness 1: _________________\n\nWitness 2: _________________""",
        "fields": ["date", "seller_name", "seller_father", "seller_age", "seller_address", "buyer_name", "buyer_father", "buyer_age", "buyer_address", "property_address", "survey_number", "area_sqft", "boundary_north", "boundary_south", "boundary_east", "boundary_west", "sale_price", "sale_price_words", "payment_mode", "token_amount", "token_date", "possession_date"],
    },
    "power_of_attorney": {
        "name": "Power of Attorney",
        "format": """# POWER OF ATTORNEY\n\nI, {principal_name}, S/o {principal_father}, Aged {principal_age} years, residing at {principal_address}, do hereby appoint:\n\n**ATTORNEY:** {attorney_name}, S/o {attorney_father}, Aged {attorney_age} years, residing at {attorney_address}\n\nAs my lawful Attorney to act on my behalf for:\n\n1. To manage, sell, transfer, mortgage my property at {property_address}\n2. To represent me before any government authority\n3. To sign documents on my behalf\n4. To collect rent, income, or dues\n5. To file tax returns and appear before IT authorities\n6. To operate bank accounts\n\n**This Power of Attorney is:** {poa_type} (Irrevocable/Revocable)\n**Valid from:** {valid_from} to {valid_to}\n\n## Signatures\n\nPrincipal (Grantor): _________________ Date: _________\n\nAttorney: _________________ Date: _________\n\nWitness 1: _________________\n\nWitness 2: _________________""",
        "fields": ["principal_name", "principal_father", "principal_age", "principal_address", "attorney_name", "attorney_father", "attorney_age", "attorney_address", "property_address", "poa_type", "valid_from", "valid_to"],
    },
    "will": {
        "name": "Last Will and Testament",
        "format": """# LAST WILL AND TESTAMENT\n\nI, {testator_name}, S/o {testator_father}, Aged {testator_age} years, residing at {testator_address}, being of sound mind and disposing memory, do hereby make this Will:\n\n## 1. Revocation\nI revoke all prior wills.\n\n## 2. Appointment of Executor\nI appoint {executor_name} as Executor of this Will.\n\n## 3. Bequests\n{bequests}\n\n## 4. Residuary Estate\nAll remaining assets to be divided equally among {residuary_beneficiaries}.\n\n## 5. Guardian of Minor Children\nI appoint {guardian_name} as guardian of my minor children.\n\n## Signature\nSignature: _________________\nDate: {date}\nPlace: {place}\n\n## Witnesses\n1. {witness1_name}, {witness1_address} _________________\n2. {witness2_name}, {witness2_address} _________________""",
        "fields": ["testator_name", "testator_father", "testator_age", "testator_address", "executor_name", "bequests", "residuary_beneficiaries", "guardian_name", "date", "place", "witness1_name", "witness1_address", "witness2_name", "witness2_address"],
    },
    "affidavit": {
        "name": "Affidavit",
        "format": """# AFFIDAVIT\n\nI, {deponent_name}, S/o {deponent_father}, Aged {deponent_age} years, residing at {deponent_address}, do hereby solemnly affirm and declare:\n\n1. That I am {relationship} of {related_person}\n\n2. That {fact1}\n\n3. {additional_facts}\n\n4. That the above statements are true and correct to the best of my knowledge and belief.\n\n**Solemnly Affirmed at {place} on this {date}**\n\nSignature: _________________\nDeponent\n\n**Before Me:**\n{Name of Notary/Oath Commissioner}\n[Stamp/Seal]\nDate: {date}""",
        "fields": ["deponent_name", "deponent_father", "deponent_age", "deponent_address", "relationship", "related_person", "fact1", "additional_facts", "place", "date", "Name of Notary/Oath Commissioner"],
    },
    "noc": {
        "name": "No Objection Certificate",
        "format": """# NO OBJECTION CERTIFICATE\n\nI, {issuer_name}, S/o {issuer_father}, Aged {issuer_age} years, residing at {issuer_address}, do hereby declare that I have no objection to:\n\n{purpose}\n\nThis NOC is valid from {valid_from} to {valid_to}.\n\n## Signature\nSignature: _________________\nDate: {date}\nPlace: {place}\n\n## Witnesses\n1. {witness1_name}, {witness1_address}\n2. {witness2_name}, {witness2_address}""",
        "fields": ["issuer_name", "issuer_father", "issuer_age", "issuer_address", "purpose", "valid_from", "valid_to", "date", "place", "witness1_name", "witness1_address", "witness2_name", "witness2_address"],
    },
}

# Minimal HTML template for PDF conversion
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
body {{ font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }}
h1 {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; }}
h2 {{ color: #283593; }}
h3 {{ color: #3949ab; }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
th {{ background: #f5f5f5; font-weight: 600; }}
.footer {{ margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 0.85em; color: #666; }}
</style>
</head>
<body>
{content}
<div class="footer">Generated by Zenix AI on {date}</div>
</body>
</html>"""


def render_template(template_name: str, variables: Dict[str, str]) -> str:
    """Render a document template with variables."""
    template = TEMPLATES.get(template_name)
    if not template:
        return f"Unknown template: {template_name}. Available: {', '.join(TEMPLATES.keys())}"
    return template["format"].format(**variables)


def list_templates() -> str:
    """List available document templates."""
    lines = ["**Available Document Templates:**\n"]
    for name, tpl in TEMPLATES.items():
        fields = ", ".join(tpl["fields"])
        lines.append(f"- **{name}**: {tpl['name']} — Fields: {fields}")
    return "\n".join(lines)


def markdown_to_html(md_text: str, title: str = "Document") -> str:
    """Convert simple markdown to HTML."""
    try:
        import markdown
        body = markdown.markdown(md_text, extensions=["tables", "fenced_code"])
    except ImportError:
        # Fallback: very basic markdown conversion
        body = _basic_md_to_html(md_text)
    return HTML_TEMPLATE.format(title=title, content=body, date=datetime.now().strftime("%d %B %Y"))


def _basic_md_to_html(text: str) -> str:
    """Fallback markdown to HTML when 'markdown' package is not installed."""
    import re
    text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'^# (.+)$', r'<h1>\1</h1>', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'```(\w+)?\n(.*?)```', r'<pre><code>\2</code></pre>', text, flags=re.DOTALL)
    text = text.replace('\n\n', '</p><p>')
    text = f'<p>{text}</p>'
    return text


def generate_pdf(html_content: str, output_path: str) -> Optional[str]:
    """Convert HTML to PDF using weasyprint or reportlab."""
    # Try weasyprint first
    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(output_path)
        return output_path
    except ImportError:
        pass

    # Try pdfkit (wkhtmltopdf)
    try:
        import pdfkit
        pdfkit.from_string(html_content, output_path)
        return output_path
    except ImportError:
        pass

    # Try reportlab with basic content extraction
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
        import re

        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Strip HTML tags for reportlab
        plain = re.sub(r'<[^>]+>', ' ', html_content)
        plain = re.sub(r'\s+', ' ', plain).strip()

        for para in plain.split('\n'):
            if para.strip():
                story.append(Paragraph(para.strip(), styles['Normal']))
                story.append(Spacer(1, 12))

        doc.build(story)
        return output_path
    except ImportError:
        pass

    logger.warning("No PDF library available. Install weasyprint or pdfkit for PDF generation.")
    return None
