"""
Document Generation — PDF export, customizable templates, formatted output.

Generates documents in Markdown, HTML, or PDF format with support for:
- Email drafts
- Reports
- Summaries
- Government forms (Aadhaar, PAN applications)
- Code snippets
"""

import os
import json
import logging
from datetime import datetime
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

TEMPLATES = {
    "email": {
        "name": "Email Draft",
        "format": """Subject: {subject}\n\nDear {recipient},\n\n{body}\n\nBest regards,\n{sender}""",
        "fields": ["subject", "recipient", "body", "sender"],
    },
    "report": {
        "name": "Report",
        "format": """# {title}\n\n**Date:** {date}\n**Author:** {author}\n\n---\n\n{body}\n\n---\n\n*Generated by Zenix AI*""",
        "fields": ["title", "date", "author", "body"],
    },
    "summary": {
        "name": "Summary",
        "format": """## {title}\n\n{body}\n\n*Summary generated on {date}*""",
        "fields": ["title", "body", "date"],
    },
    "form_letter": {
        "name": "Form Letter",
        "format": """{date}\n\n{recipient_name}\n{recipient_address}\n\nSubject: {subject}\n\nDear {recipient_name},\n\n{body}\n\nSincerely,\n{sender_name}""",
        "fields": ["date", "recipient_name", "recipient_address", "subject", "body", "sender_name"],
    },
    "code": {
        "name": "Code Snippet",
        "format": """# {title}\n\n```{language}\n{code}\n```\n\n## Explanation\n\n{explanation}""",
        "fields": ["title", "language", "code", "explanation"],
    },
    "memo": {
        "name": "Internal Memo",
        "format": """MEMORANDUM\n\nTO: {to}\nFROM: {from_name}\nDATE: {date}\nRE: {subject}\n\n{body}""",
        "fields": ["to", "from_name", "date", "subject", "body"],
    },
}

# Minimal HTML template for PDF conversion
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
body {{ font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }}
h1 {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; }}
h2 {{ color: #283593; }}
h3 {{ color: #3949ab; }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
th {{ background: #f5f5f5; font-weight: 600; }}
.footer {{ margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 0.85em; color: #666; }}
</style>
</head>
<body>
{content}
<div class="footer">Generated by Zenix AI on {date}</div>
</body>
</html>"""


def render_template(template_name: str, variables: Dict[str, str]) -> str:
    """Render a document template with variables."""
    template = TEMPLATES.get(template_name)
    if not template:
        return f"Unknown template: {template_name}. Available: {', '.join(TEMPLATES.keys())}"
    return template["format"].format(**variables)


def list_templates() -> str:
    """List available document templates."""
    lines = ["**Available Document Templates:**\n"]
    for name, tpl in TEMPLATES.items():
        fields = ", ".join(tpl["fields"])
        lines.append(f"- **{name}**: {tpl['name']} — Fields: {fields}")
    return "\n".join(lines)


def markdown_to_html(md_text: str, title: str = "Document") -> str:
    """Convert simple markdown to HTML."""
    try:
        import markdown
        body = markdown.markdown(md_text, extensions=["tables", "fenced_code"])
    except ImportError:
        # Fallback: very basic markdown conversion
        body = _basic_md_to_html(md_text)
    return HTML_TEMPLATE.format(title=title, content=body, date=datetime.now().strftime("%d %B %Y"))


def _basic_md_to_html(text: str) -> str:
    """Fallback markdown to HTML when 'markdown' package is not installed."""
    import re
    text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'^# (.+)$', r'<h1>\1</h1>', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'```(\w+)?\n(.*?)```', r'<pre><code>\2</code></pre>', text, flags=re.DOTALL)
    text = text.replace('\n\n', '</p><p>')
    text = f'<p>{text}</p>'
    return text


def generate_pdf(html_content: str, output_path: str) -> Optional[str]:
    """Convert HTML to PDF using weasyprint or reportlab."""
    # Try weasyprint first
    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(output_path)
        return output_path
    except ImportError:
        pass

    # Try pdfkit (wkhtmltopdf)
    try:
        import pdfkit
        pdfkit.from_string(html_content, output_path)
        return output_path
    except ImportError:
        pass

    # Try reportlab with basic content extraction
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
        import re

        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Strip HTML tags for reportlab
        plain = re.sub(r'<[^>]+>', ' ', html_content)
        plain = re.sub(r'\s+', ' ', plain).strip()

        for para in plain.split('\n'):
            if para.strip():
                story.append(Paragraph(para.strip(), styles['Normal']))
                story.append(Spacer(1, 12))

        doc.build(story)
        return output_path
    except ImportError:
        pass

    logger.warning("No PDF library available. Install weasyprint or pdfkit for PDF generation.")
    return None
